### ISSUE TITLE
net commander

### ISSUE THREAD

**Issue by gbaumgart** [hobbyquaker/awesome-mqtt#10]
hi, 
thanks for mentioning netcommander on your cool list. 

Could you please point to the new url: https://github.com/net-commander/windows-dist

thanks a lot,
guenter

**Comment by xblox** [comment]
Hey Sebastian, 
sorry for the mess, if you could re-add https://github.com/xblox/control-freak (IoT/RAD IDE). I just managed to release a final first version these days. 

Thanks a lot! Your guide is btw. in our company's resource list :-)

**Comment by hobbyquaker** [comment]
done :)
