### ISSUE TITLE
Unsure about how to include my software StudioDisplay

### ISSUE THREAD

**Issue by Moonbase59** [hobbyquaker/awesome-mqtt#31]
Hi, I’d be glad if you could include my **StudioDisplay** in your list, but I’m unsure about all this PR stuff and if you would include it as a whole system or each module separately (some modules might be useful for others if used separately).

**StudioDisplay** is a fast, modular MQTT-based signalling & display solution for Web Radio Stations using IDJC. Or just to make your smart home even smarter.

It’s available here: https://github.com/Moonbase59/studiodisplay

All modules adhere to the [mqtt-smarthome architecture proposal](https://github.com/mqtt-smarthome/mqtt-smarthome) and I’d be happy if they’d be included in your software list.

StudioDisplay currently contains these modules:

* **StudioDisplay:** Shows it all on the big screen (Raspberry Pi 3B/3B+ required, [_Blinkt_](https://shop.pimoroni.com/products/blinkt) module recommended).
* **mqtt-weather-wunderground:** Weather data provider, includes 3-day forecast (free Wunderground API key required).
* **mqtt-astronomy:** Sunrise, sunset, moonrise, moonset, moon phase and phases of the day. Can be used to control ambient lighting and anything dependent on the phase of the day.
* **mqtt-callmonitor-fritz:** Call monitor for [AVM Fritz!Box](https://en.avm.de/products/fritzbox/) routers, can also notify/control a [KODI](https://kodi.tv/)/[LibreELEC](https://libreelec.tv/) media player.
* **mqtt-radio:** Live radio stream metadata display.
* **mqtt-idjc:** Monitor for [IDJC (Internet DJ Console)](http://idjc.sourceforge.net/), provides studio signalling.
* **mqtt-signalbox (SignalBox):** Interface to professional signal towers & »On Air« door light (SignalBox or IOWarrior relais card required).
* **mqtt-signalpi (SignalPi):** The »poor man’s signal tower« (typically used on a Raspberry Pi Zero W, [_Blinkt_](https://shop.pimoroni.com/products/blinkt) module required).
* **mqtt-unicornlight (UnicornLight):** Experimental mini »ambient light« (Raspberry Pi Zero W or better and [_Unicorn pHAT_](https://shop.pimoroni.com/products/unicorn-phat) or [_Unicorn HAT_](https://shop.pimoroni.com/products/unicorn-hat) required).

**Comment by hobbyquaker** [comment]
My 2 Cent:
If these modules can be installed and used standalone I would suggest one entry for each module. If they are dependent on each other and can only be installed as complete bundle I would make one list entry only.
