### ISSUE TITLE
MQTTLens

### ISSUE THREAD

**Issue by GermanBluefox** [hobbyquaker/awesome-mqtt#8]
I use by the developing MQTTLens tool as client.
https://chrome.google.com/webstore/detail/mqttlens/hemojaaeigabkbcookmlgmdigohjobjm
Very laconic and easy to use client.

To fullfill the list of MQTT Brokers, it should be extended with all HomeAutomations platforms with MQTT support: z.B. ioBroker :)

**Comment by hobbyquaker** [comment]
Hi Bluefox,
I added MQTTLens, thanks for the Hint.
ioBroker is (of course ;-) already on the list: https://github.com/hobbyquaker/awesome-mqtt#smart-home-building-automation
Regards,
Sebastian
